name: Docker Image CI

env:
  DOCKER_IMAGE: "transcript"
  DOCKER_TAG: "build"
  A: &DOCKER_IMAGE
  
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build . --tag $DOCKER_IMAGE:$DOCKER_TAG
        docker tag $DOCKER_IMAGE:$DOCKER_TAG ${{ secrets.DOCKER_USERNAME }}/$DOCKER_IMAGE
        docker push ${{ secrets.DOCKER_USERNAME }}/$DOCKER_IMAGE
